name: CD

on:
  release:
    types: [created]

jobs:
  make-release:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:

      - name: Checkout project
        uses: actions/checkout@v2

      - name: Setup miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest" 
          python-version: "3.8"
          channel-priority: "flexible"
          channels: "conda-forge"  
          mamba-version: "*"
          show-channel-urls: true 

      - name: Setup project dependencies
        run: |
          mamba install --file requirements/conda_run.txt -c semi-ate -y -q
          mamba install --file requirements/conda_test.txt -c semi-ate -y -q

      - name: Tag to version
        run: echo "__version__='${GITHUB_REF#refs/*/}'" >> QScreenCast/__init__.py

      - name: Run tests
        run: pytest tests/ --cov=QScreenCast

      - name: Create package
        run: python setup.py sdist 

      - name: Check package
        run: twine check dist/*

      - name: Check manifest
        run: check-manifest

      - name: Upload to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: python -m twine upload dist/*

      # - name: Upload coverage to Codecov  
      #   uses: codecov/codecov-action@v1
      #   with:
      #    token: ${{ secrets.CODECOV_TOKEN }}

