name: CD

on:
  release:
    types: [created]

jobs:
  make-release:
     runs-on: ubuntu-latest
    steps:

      - name: Checkout project
        uses: actions/checkout@v2

      - name: Setup miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest" 
          python-version: "3.8"
          channel-priority: "strict"
          channels: "conda-forge"  
          mamba-version: "*"
          show-channel-urls: true 

      - name: Setup project dependencies
        run: |
          mamba install -n test --file requirements/run.txt -c conda-forge -y -q
          mamba install -n test --file requirements/test.txt -c conda-forge -y -q
      - name: Run tests
        shell: bash -l {0}
        run: pytest tests/ --cov=QScreenCast

      - name: Create package
        shell: bash -l {0}
        run: python setup.py sdist 

      - name: Check package
        shell: bash -l {0}
        run: twine check dist/*

      - name: Check manifest
        shell: bash -l {0}
        run: check-manifest

      - name: Upload to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: python -m twine upload dist/*

      - name: Upload coverage to Codecov  
        uses: codecov/codecov-action@v1
        with:
         token: ${{ secrets.CODECOV_TOKEN }}

