name: CD

on:
  release:
    types: [created]

jobs:
  make-release:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout project
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
          pip install -r requirements/run.txt
          pip install -r requirements/test.txt

    - name: Tag to version
      run: echo "__version__='${GITHUB_REF#refs/*/}'" >> QScreenCast/__init__.py

    - name: Run tests
      run: pytest tests/ --cov=starz

    - name: Create package
      run: python setup.py sdist

    - name: Check package
      run:  twine check dist/*

    - name: Check manifest
      run: check-manifest
    - run: ls -la dist/*

#    - name: Upload to PyPI
#      env:
#        TWINE_USERNAME: __token__
#        TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
#      run: python -m twine upload dist/*

    # - name: Upload coverage to Codecov  
    #   uses: codecov/codecov-action@v1
    #   with:
    #     token: ${{ secrets.CODECOV_TOKEN }}

