name: CD

on:
  release:
    types: [created]

jobs:
  make-release:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout project
        uses: actions/checkout@v2

      - name: Install mamba & environment
        uses: mamba-org/provision-with-micromamba@v11
        with:
          environment-file: ./requirements/mamba_environment.yaml

      - name: Tag to version
        run: echo "__version__='${GITHUB_REF#refs/*/}'" >> QScreenCast/__init__.py

      - name: Run tests
        shell: bash -l {0}
        run: pytest tests/ --cov=QScreenCast

      - name: Create package
        shell: bash -l {0}
        run: python setup.py sdist 

      - name: Check package
        shell: bash -l {0}
        run: twine check dist/*

      - name: Check manifest
        shell: bash -l {0}
        run: check-manifest

      - name: Upload to PyPI
        shell: bash -l {0}
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: python -m twine upload dist/*

      # - name: Upload coverage to Codecov  
      #   uses: codecov/codecov-action@v1
      #   with:
      #    token: ${{ secrets.CODECOV_TOKEN }}

