name: CI

on: [push]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
        
      - name: Setup miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest" 
          python-version: "3.8"
          channel-priority: "flexible"
          channels: "conda-forge"  
          mamba-version: "*"
          show-channel-urls: true 

      - name: Setup project dependencies
        run: |
          mamba install -n test --file requirements/conda_run.txt -c semi-ate -y -q
          mamba install -n test --file requirements/conda_test.txt -c semi-ate -y -q
          
      - name: Run tests
        run: pytest tests/ --cov=QScreenCast

      - name: Create package
        run: python setup.py sdist 

      - name: Check package
        run: twine check dist/*

      - name: Check manifest
        run: check-manifest
