name: CI

on: [push]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
        
      - name: Setup miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.9
          mamba-version: 0.16.0
          channels: conda-forge, semi-ate
          channel-priority: flexible        
          show-channel-urls: true 

      - name: Setup environment
        run: |
          mamba install --file requirements/conda_run.txt -y -q
          mamba install --file requirements/conda_test.txt -y -q 
          
      - name: Run tests
        run: pytest tests/ --cov=QScreenCast

      - name: Create package
        run: python setup.py sdist 

      - name: Check package
        run: twine check dist/*

      - name: Check manifest
        run: check-manifest
