name: CI

on: [push]

jobs:
  test-linux:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout project
        uses: actions/checkout@v2

      - name: Setup miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest" 
          python-version: "3.8"
          channel-priority: "strict"
          channels: "conda-forge"  
          mamba-version: "*"
          show-channel-urls: true 

      - name: Setup project dependencies
        run: |
          mamba install --file requirements/run.txt -c conda-forge -y -q
          mamba install --file requirements/test.txt -c conda-forge -y -q

      - name: Run tests
        run: pytest tests/ --cov=QScreenCast

      - name: Create package
        run: python setup.py sdist 

      - name: Check package
        run: twine check dist/*

      - name: Check manifest 
        run: check-manifest
