name: CI

on: [push]

jobs:
  test-linux:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout project
        uses: actions/checkout@v2

      - name: Install mamba & environment
        uses: mamba-org/provision-with-micromamba@v11
        with:
          environment-file: requirements/mamba_environment.yaml

      - name: Run tests
        shell: bash -l {0}
        run: pytest tests/ --cov=QScreenCast

      - name: Create package
        shell: bash -l {0}
        run: python setup.py sdist 

      - name: Check package
        shell: bash -l {0}
        run: twine check dist/*

      - name: Check manifest
        shell: bash -l {0}
        run: check-manifest
